app = "primatejs"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile.fly-website"

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 6161
  processes = ["app"]
  script_checks = []
  [services.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
    tls_options = { "alpn" = ["h2", "http/1.1"], "versions" = ["TLSv1.2", "TLSv1.3"] }

  [services.http_checks]
    interval = 30000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

