module Session

from "json" include Json
from "primate/request" include Request
from "primate/response" include Response
from "primate/session" include Session
from "option" include Option
use Session.{ type Session }
use Request.{ type Request }
use Response.{ type Response }

provide let get = (request: Request) => {
  Session.create(Json.JsonObject([("foo", Json.JsonString("bar"))]))
  let session =  Option.expect("Expect session to exist", Session.get())
  Response.json(session.data)
}
