source "https://rubygems.org"

group :development do
  gem "ruby-lsp"
  gem "rbs"
end

primate_version = ENV["PRIMATE_RUN_VERSION"] || "~> 0.3.0"

if (path = ENV["PRIMATE_RUN_PATH"]) && !path.empty?
  gem "primate-run", path: path
else
  gem "primate-run", primate_version
end
