import priss from "./module.js";
import FileRef from "@rcompat/fs/FileRef";

export default priss({
  blog: true,
  title: "Primate",
  description: "The universal web framework",
  root: FileRef.join("components", "content"),
  theme: {
    navbar: [
      { label: "Guide", link: "/guide/getting-started" },
      { label: "Modules", link: "/modules/official" },
      { label: "Blog", link: "/blog" },
    ],
    sidebar: {
      guide: [
        { heading: "Introduction" },
        "Getting started",
        "Project structure",
        "Configuration",
        "Use cases",
        { heading: "Concepts" },
        "Routes",
        "Responses",
        "Types",
        "Guards",
        "Components",
        "Layouts",
        "Errors",
        "Sessions",
        { heading: "Modules" },
        "Extending Primate",
        "Hooks",
        { heading: "Extras" },
        "Logging",
      ],
      errors: [
        { heading: "Errors" },
        "Core",
        "Frontend",
        "Go",
        "HTMX",
        "I18N",
        "Store",
        "WebC",
      ],
      modules: [
        { heading: "Modules" },
        "Official",
        "Third-party",
        "Runtime support",
        { heading: "Frontends" },
        "Frontend",
        "Angular",
        "Eta",
        "Handlebars",
        "HTML",
        "HTMX",
        "Markdown",
        "Marko",
        "Poly",
        "React",
        "Solid",
        "Svelte",
        "Voby",
        "Vue",
        "Web Components",
        { heading: "Data" },
        "Schema",
        "Store",
        "Drivers",
        { heading: "Backends" },
        "Backend",
        "Go",
        "Python",
        "Ruby",
        "TypeScript",
        { heading: "Others" },
        "Native",
        "I18N",
      ],
    },
    github: "primate-run/primate",
    x: "primate_run",
    chat: "https://discord.gg/RSg4NNwM4f",
  },
});
