module Ws

from "primate/request" include Request
from "primate/response" include Response
from "primate/websocket" include WebSocket

use Response.{ type Response }
use Request.{ type Request }
use WebSocket.{ type SocketMessage, type WebSocket, send }

provide let get = (req: Request) => {
  Response.ws(
    open = Some((_socket) => {
      print("Opened!")
    }),
    message = Some((socket: WebSocket, payload: SocketMessage) => {
      send(socket, payload)
    }),
  )
}
