name: koyeb.com deployment

on:
  push:
    branches: ["master"]

jobs:
  deploy-website:
    if: github.repository_owner == 'primatejs'
    runs-on: ubuntu-latest

    steps:
      - name: Install Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"
      - name: Build and deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: "website"
          service-name: "primate"
          service-instance-type: "free"
          service-regions: "fra"
          service-ports: "6161:http"
          service-routes: "/:6161"
          service-checks: "6161:http:/"
          skip-cache: true
          git-workdir: "./"
          git-branch: "master"
          git-builder: "docker"
          git-docker-dockerfile: "./packages/website/Dockerfile"
      - name: "Purge Fastly cache"
        run: |
          curl -X POST -H "Fastly-Key: ${{ secrets.FASTLY_API_KEY }}" \
          "https://api.fastly.com/service/${{ secrets.FASTLY_SERVICE_ID }}/purge_all"
