name: render.com deployment

on:
  push:
    branches: ["master"]

jobs:
  deploy-website:
    if: github.repository_owner == 'primatejs'
    runs-on: ubuntu-latest

    steps:
      - name: Use Render API
        uses: sws2apps/render-deployment@v1.7.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false
